module Context = ApolloClient__React_Context
module Hooks = ApolloClient__React_Hooks
module Types = ApolloClient__React_Types

let useLazyQuery = ApolloClient__React_Hooks_UseLazyQuery.useLazyQuery
let useMutation = ApolloClient__React_Hooks_UseMutation.useMutation
let useQuery = ApolloClient__React_Hooks_UseQuery.useQuery
let useSubscription = ApolloClient__React_Hooks_UseSubscription.useSubscription
