module ApolloClient = ApolloClient__Core_ApolloClient
module LocalState = ApolloClient__Core_LocalState
module NetworkStatus = ApolloClient__Core_NetworkStatus.NetworkStatus
module ObservableQuery = ApolloClient__Core_ObservableQuery
module Types = ApolloClient__Core_Types
module WatchQueryOptions = ApolloClient__Core_WatchQueryOptions
