module UseApolloClient = ApolloClient__React_Hooks_UseApolloClient
module UseMutation = ApolloClient__React_Hooks_UseMutation
module UseQuery = ApolloClient__React_Hooks_UseQuery
module UseSubscription = ApolloClient__React_Hooks_UseSubscription
