let getOperationDefinition = ApolloClient__Utilities_Graphql_GetFromAst.getOperationDefinition

module Graphql = ApolloClient__Utilities_Graphql
module Observables = ApolloClient__Utilities_Observables
module Policies = ApolloClient__Utilities_Policies
